apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-namespaces
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/slava-shishkin4032/eks-gitops-platform.git
    targetRevision: main
    path: platform/namespaces

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true